### ISSUE TITLE
Algebraic coding theory probably misplaced on the dependency chart?

### ISSUE THREAD

**Issue by geo909** [twjudson/aata#11]
Hi, 

Thanks a lot for this open source textbook. 

Algebraic coding theory appears to be a dependency for chapters 9 and beyond in the 
dependency chart in the preface. I would think that it should be an individual branch, such 
as chapters 6 and 7. 

Is that indeed an omission or is there a good reason for that?

Thanks a lot

**Comment by Jahrme** [comment]
I believe you may be misreading the dependency chart (viewable [here](http://abstract.pugetsound.edu/aata/preface-1.html)). The dashed lines are read in the same way as the solid lines with the difference that a dashed line represents a *partial* dependency.

So, the dashed line connecting Chapter 8 (Algebraic Coding theory) to Chapter 22 (Finite Fields) means that Chapter 22 is partially dependent on Chapter 8.

**Comment by geo909** [comment]
So sorry, my bad. I just realized that I was using a very old printed edition (1997) where the diagram seems to be erroneous. I should have been more careful.

Thanks again.

**Comment by twjudson** [comment]
No worries.  There have been lots changes since 1997.  See http://abstract.ups.edu/index.html

Tom Judson

=========
Thomas W. Judson, Associate Professor
Department of Mathematics and Statistics
Stephen F. Austin State University
P.O. Box 13040-3040 SFA Station
Nacogdoches, TX  75962

OFFICE: 316 Math
TEL: (936) 468-1704
EMAIL: judsontw@sfasu.edu<mailto:judsontw@sfasu.edu>




On Dec 29, 2016, at 9:29 PM, geo909 <notifications@github.com<mailto:notifications@github.com>> wrote:


So sorry, my bad. I just realized that I was using a very old printed edition (1997) where the diagram seems to be erroneous. I should have been more careful.

Thanks again.
