### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sclel016** [twjudson/aata#13]
Solutions of Section 1.3, Question 25a. The solution reads "NThe" instead of "The".

**Comment by twjudson** [comment]
Exercise 25 (and the solution) in Chapter 1 look fine to me.  Can you be more specific on the location of this typo,  I can’t find it.

Tom Judson

=========
Thomas W. Judson, Associate Professor
Department of Mathematics and Statistics
Stephen F. Austin State University
P.O. Box 13040-3040 SFA Station
Nacogdoches, TX  75962

OFFICE: 316 Math
TEL: (936) 468-1704
EMAIL: judsontw@sfasu.edu<mailto:judsontw@sfasu.edu>




On Mar 8, 2017, at 4:00 PM, sclel016 <notifications@github.com<mailto:notifications@github.com>> wrote:


Solutions of Section 1.3, Question 25a. The solution reads "NThe" instead of "The".

**Comment by sclel016** [comment]
See [Picture](http://imgur.com/a/tBNHw). It's in the 2016 Print Edition on page 394 and the 2016 PDF on page 308. It may have been fixed in the mean time in the repo, I haven't compiled my own PDF version.

Stew

**Comment by twjudson** [comment]
I don’t remember fixing this, but it’s not there now.

Tom

On May 16, 2017, at 7:04 PM, sclel016 <notifications@github.com<mailto:notifications@github.com>> wrote:


See Picture<https://urldefense.proofpoint.com/v2/url?u=http-3A__imgur.com_a_tBNHw&d=AwMCaQ&c=2X_btuPRWkGwRX26NHIotw&r=HHnSin1HiVqECkGNr3CYMMVKoIg6gqvvI8vNSKP3c70&m=uZ-eQBWVQf33N-IPaIqIPDAOJ0p0TjQYVQxgP6fFzGE&s=i27Jkf6VOGIfT0Q0nqIj5HOIRUQDgGRhKLcLzNp_XPU&e=>. It's in the 2016 Print Edition on page 394 and the 2016 PDF on page 308. It may have been fixed in the mean time in the repo, I haven't compiled my own PDF version.

Stew

**Comment by rbeezer** [comment]
Second hunk here:  https://github.com/twjudson/aata/commit/2be9d4abd2c3f5833e436c36c49c95681cc4586a  ;-)
