### ISSUE TITLE
Potential typo in Chapter 3 Groups, Section on Sage (3.7) (2016 version)

### ISSUE THREAD

**Issue by janusboandersen** [twjudson/aata#14]
Dear authors / editors,

2016 version of AATA including Sage Exercises.
Regarding section 3.7, subsection Groups of symmetries:

In the final Cayley table for the section, rows and columns of the table are named in the following order id u1 u3 r1 r2 u2. I believe there is a typo here. Look for instance at an example: applying the rotation r1 twice, per the table yields the reflection u3. This cannot be true, it should yield r2.

A fix should be fast, I believe the correct order of permutation names to correspond to the table output by Sage is as follows:

#Build the Cayley table
aata_names = ['id', 'u3', 'r1', 'r2', 'u1', 'u2']
triangle.cayley_table(names=aata_names)

Thank you for a great book!

Best regards,
Janus

**Comment by rbeezer** [comment]
Very nice catch, Janus.  That mistake was introduced in May 2015, since Sage output for permutation groups got re-ordered at b74199c8.  I failed to notice that those names are from the narrative and only align with the Sage elements because a human has to figure out.  Therefore our automatic testing regime failed to point out the inconsistency.  And your proposed fix is correct.

So, thanks very much for noticing and taking the time to report it.  Fixed at d9ba989f which should go public sometime over the summmer (or sooner for the web version).

Rob
