### ISSUE TITLE
Footnote 2's content appears on the next page

### ISSUE THREAD

**Issue by adannyreyes** [twjudson/aata#46]
In the PDF of the 2020 edition, the reference for footnote 2 is on page 67, but its content appears on the next page. This is somewhat confusing because it makes it look like the "2" reference on page 67 is a typo.

Refs commit 2088bb9, issue #35

**Comment by twjudson** [comment]
I can fix the problem, but as soon as someone reformats for a different page size, the problem will reappear.  Therefore, it’s something that is  inherit in PreTeXt.

On Sep 25, 2020, at 11:44 AM, Antonius Danny Reyes <notifications@github.com<mailto:notifications@github.com>> wrote:



In the PDF of the 2020 edition, the reference for footnote 2 is on page 67, but its content appears on the next page. This is somewhat confusing because it makes it look like the "2" reference on page 67 is a typo.

Refs commit 2088bb9<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_twjudson_aata_commit_2088bb963101238d790b009dc198261a4198bc9e&d=DwMCaQ&c=2X_btuPRWkGwRX26NHIotzR6MNUgJAbf6yNNV5-qTbU&r=BQmZUphR5rjzEsIGWo4gOhHhb8A_MVZPtDOMQxdFlh8&m=uq6yRRHbTr2F9Z58qJ3Q3RqF-MpaTZ4oSNI5oPnBiWY&s=RBrqFYgKpd1bkAgaJnOliiPHzuDViEyB3LE9qjDOIQY&e=>, issue #35<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_twjudson_aata_issues_35&d=DwMCaQ&c=2X_btuPRWkGwRX26NHIotzR6MNUgJAbf6yNNV5-qTbU&r=BQmZUphR5rjzEsIGWo4gOhHhb8A_MVZPtDOMQxdFlh8&m=uq6yRRHbTr2F9Z58qJ3Q3RqF-MpaTZ4oSNI5oPnBiWY&s=1BZS1C70LTFmlkTGTEm6f-HVqyYEcCoF8KdQ6cSI26Q&e=>

**Comment by twjudson** [comment]
I can fix the problem, but as soon as someone reformats for a different page size, the problem will reappear.  Therefore, it’s something that is  inherit in PreTeXt.
